### ISSUE TITLE
Discussion : Consul API Gateway on Minikube Cluster Mac

### ISSUE THREAD

**Issue by PrateekKhatri** [hashicorp-education/learn-consul-api-gateway#2]
Hi,
I have setup consul api gateway on minikube cluster on mac, but I am not able to access the sample applications. Do we need to setup some extra configuration ? 

Please suggest. 

Thank you.

**Comment by krastin** [comment]
Hi Prateek,

Apologies for the delayed response.
Consul API gateway for K8s relies on the K8s platform to provision a functioning load-balancer ingress service.
Local K8s solutions like KIND and Minikube offer different levels of support for the load-balancer entity and sometimes are dependent on the OS (port-forwarding with Docker on OSX) or on another solution like MetalLB.
With that in mind, our repository here is aimed at cloud solutions that support this functionality out-of-the-box.
However, you are free to adapt the code and make it work for a local solution - that would make for a great learning journey for both K8s and Consul skills.

I'll go ahead and close this issue.

Regards,
Krastin
